services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - AUTH_TOKEN=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - PORT=3000
    volumes:
      - ./data_cache.json:/app/data_cache.json
    restart: always